<?php 
$libPath = "https://cdn.turista.mx/_lib";
$bootstrapPath = $libPath . '/bootstrap-3.3.6';
?>


<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->config['siteName'])->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($bootstrapPath . '/css/docs.min.css')
                        ->prependStylesheet($bootstrapPath . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($bootstrapPath . '/css/bootstrap.min.css') 
        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($bootstrapPath . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        
        ; ?>

    </head>
    <body >
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
            
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    
                    
                    
                    <a href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/logo.gif') ?>" alt="<?php $this->config['siteName']?>" height="50px"/></a>
                </div>
                
                <div class="collapse navbar-collapse">
                    <?php echo $this->navigation('navigation')
                    ->menu()
                    ->setPartial('partial/navigation')?>
                </div><!--/.nav-collapse -->
                
                
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by <a href="https://www.turista.com.mx">Turista.com.mx</a> S.A. de C.V. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>

        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
       
    </body>
</html>
