<div class="btn-group">
                                <a class="btn btn-default" href="#">
                                    <i class="fa fa-star"></i>
                                </a>                                         
                                <a class="btn btn-default" href="#" id="modal-update-trigger">
                                Modal
                                </a>
                                <a class="btn btn-default" href="#">
                                    <i class="fa fa-cog"></i>
                                </a>
                            </div><!-- End .btn-group -->
			<a href="#modal-update"
			   class="btn btn-default"
			   data-toggle="modal"
			   data-remote="<?php echo $this->url('noticias', array('action' => 'add'));?>"
			   data--target="#form_edit">
			   <i class="fa fa-file-text-o"></i>
			   <span>Agregar Estado</span></a>